---
latitude: 40.70523
longitude: -74.00638
map_zoom: 12
name: Eurostars Wall Street
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 129 Front Street
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10005'
_hotel_id: EUR486
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
